package com.una.carassistschedulebackend.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.math.BigDecimal;

@DynamoDBTable(tableName = "service")
public class Assistance {
    private String id;
    private String assistanceType;
    private BigDecimal price;

    public Assistance() { super(); }
    public Assistance(String assistanceType, BigDecimal price) {
        super();
        this.assistanceType = assistanceType;
        this.price = price;
    }

    @DynamoDBHashKey(attributeName = "serviceId")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "serviceType")
    public String getServiceType() {
        return assistanceType;
    }

    public void setServiceType(String serviceType) {
        this.assistanceType = serviceType;
    }

    @DynamoDBAttribute(attributeName = "price")
    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }

    @Override
    public String toString() {
        return super.toString();
    }
}
