package com.una.entidades;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.una.models.ServiceType;

@DynamoDBTable(tableName = "schedule")
public class Schedule {
    private String id;
    private Date date;
    private String price;
    private ServiceType serviceType;
    private String clientName;
    private String clientCar;


    public Schedule() {
    }

    public Schedule(String id, Date date, String price, ServiceType serviceType, String clientName, String clientCar) {
        this.id = id;
        this.date = date;
        this.price = price;
        this.serviceType = serviceType;
        this.clientName = clientName;
        this.clientCar = clientCar;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @DynamoDBAttribute
    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    @DynamoDBAttribute
    public ServiceType getServiceType() {
        return this.serviceType;
    }

    public void setServiceType(ServiceType serviceType) {
        this.serviceType = serviceType;
    }

    @DynamoDBAttribute
    public String getClientName() {
        return this.clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    @DynamoDBAttribute
    public String getClientCar() {
        return this.clientCar;
    }

    public void setClientCar(String clientCar) {
        this.clientCar = clientCar;
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }

    @Override
    public String toString() {
        return super.toString();
    }
}